### ISSUE TITLE
Jupyter Book repo structure and docs on where session leaders should drop things

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/jupyter_days#2]
@TomasBeuzen - can you add the skeleton for the jupyter book here? Also, can you add some docs somewhere (just a few sentences in a README perhaps) telling session leaders where they should put the notebooks for their session so they can become part of the book? And any other pertinent info they should know?

**Comment by TomasBeuzen** [comment]
Should be able to do this by early next week.

**Comment by TomasBeuzen** [comment]
Done. Instructions added [here](https://github.com/UBC-DSCI/jupyter_days#instructor-instructions). The book is being automatically built [here](https://ubc-dsci.github.io/jupyter_days/content/introduction.html). I'll keep an eye on the builds and instructors can get in touch with me if they are having problems.

**Comment by TomasBeuzen** [comment]
ps. sorry for the hex - I like adding colour to my books :D We can change it to whatever.

**Comment by ttimbers** [comment]
I like the colours 😂 , but I guess we'll have to let others weigh in too :)

**Comment by patrickwalls** [comment]
I think it looks like the [Pride Flag](https://en.wikipedia.org/wiki/Rainbow_flag_(LGBT)) which I don't think is ours to use. Perhaps we could get permission to use the Jupyter logo along with the UBC logo.

**Comment by patrickwalls** [comment]
Or just use the UBC fonts and colors: https://brand.ubc.ca/guidelines/downloads/ubc-colour-and-fonts/

**Comment by patrickwalls** [comment]
I would prefer to use UBC colors and fonts: https://brand.ubc.ca/guidelines/downloads/ubc-colour-and-fonts/

I think this will be helpful to our colleagues at CTLT to promote the event. In fact, they might want to make something for us.

**Comment by TomasBeuzen** [comment]
Will open in a new issue.
