### ISSUE TITLE
JupyterDays hex/logo

### ISSUE THREAD

**Issue by TomasBeuzen** [UBC-DSCI/jupyter_days#4]
It would be nice to have a hex sticker or logo to help promote the workshop. Here are two examples:

- Using a "planet Jupiter" colour palette

<img src="https://user-images.githubusercontent.com/40379073/86799596-fa5e5d80-c026-11ea-803d-0885e7dd3110.png" width="300"/>

- Using UBC colours/font
<img src="https://user-images.githubusercontent.com/40379073/86800166-95efce00-c027-11ea-9766-570391988ba5.png" width="300"/>

Feel free to leave any comments below - it might be cool to include the Jupyter logo somewhere, we could ask for their permission. @patrickwalls has also suggested we could ask CTLT to create the logo for us - if that's the case, perhaps one of the key organisers can get in touch with them.

**Comment by prosoitos** [comment]
I like the planet Jupyter colour palette one!

**Comment by patrickwalls** [comment]
We now have an image including UBC colours, fonts and photography. This will help to get UBC communications channels to promote our event.
