### ISSUE TITLE
Talk topic

### ISSUE THREAD

**Issue by prosoitos** [UBC-DSCI/jupyter_days#8]
I thought that I would give a talk to demo the use of the Julia kernel in Jupyter, but I noticed that another Julia talk (I have no doubt much better than what I would do) just got added to the schedule.

So I am now debating between 2 approaches and I thought I'd ask what people think:

## Option 1

Keep the topic of Julia in Jupyter, but make sure there is no overlap with @arnavs's material by focusing, not on using Julia in Jupyter, but instead on how to go back and forth between Julia scripts and Jupyter notebooks (so packages such as [NBInclude](https://github.com/stevengj/NBInclude.jl), [Literate](https://github.com/fredrikekre/Literate.jl), and [ipynb2LiterateJulia](https://github.com/oxinabox/ipynb2LiterateJulia)).

## Option 2

Change topic entirely.

One subject I'd be excited to present, but maybe you'll think that it is targeting too small an audience, is how to run Jupyter notebooks within Emacs with the package [EIN](https://github.com/millejoh/emacs-ipython-notebook).

---

Comments and thoughts welcome! Thanks :slightly_smiling_face:

**Comment by patrickwalls** [comment]
It turns out that Arnav is unavailable. But we have @wupeifan who will talk about QuantEcon. We can coordinate our talks. I would still like to hear about Julia and Jupyter in more detail.

**Comment by prosoitos** [comment]
Is @wupeifan talking about QuantEcon in Python or Julia? (If Python, then I'll def give a talk on Julia. If Julia, then I'll chat with him about what he'll cover in terms of Julia in Jupyter).

**Comment by wupeifan** [comment]
It will be on Python. Basically I'll talk about QuantEcon Datascience https://datascience.quantecon.org/ that we used as teaching material this spring. 
If you want me to talk a bit about IJulia I can also do that. @prosoitos

**Comment by prosoitos** [comment]
No, no: the talk is really up to you. The only reason I am asking is because I don't want to give a redundant talk. So if you are covering Julia in Jupyter as part of your talk, I think that I should choose another topic. But if you are not covering it, since @patrickwalls is interested in having something on Julia, I can do that. So it is really up to you. I just need to know to decide which way to go. Thanks!! :slightly_smiling_face:

**Comment by wupeifan** [comment]
Sure, I guess I'll mainly cover the QEDS thing that I taught this spring. Then I won't talk about Julia (maybe mention in 1-2 sentences that Jupyter can support multiple language cores... but no more than that)

**Comment by prosoitos** [comment]
OK. Thanks for the info!
